name: ci_octave

on: [push, pull_request]

jobs:

  counting:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - run: sudo apt install -yq --no-install-recommends octave
    - run: octave test_motion.m
