name: ci_python

on: [push, pull_request]

jobs:

  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - run: pip install -e .[lint]
    - run: flake8
    - run: mypy .

  count:
    needs: [lint]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - run: pip install -e .[tests]
    - run: pytest -r a -v
